development:
  adapter: async
  # adapter: redis

test:
  adapter: async
  # adapter: redis

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: disclone_production
